//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHotels.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HappyHotelsEntities : DbContext
    {
        public HappyHotelsEntities()
            : base("name=HappyHotelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amenity> Amenities { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HotelAmenity> HotelAmenities { get; set; }
        public virtual DbSet<HotelContact> HotelContacts { get; set; }
        public virtual DbSet<HotelLandmark> HotelLandmarks { get; set; }
        public virtual DbSet<HotelPhoto> HotelPhotoes { get; set; }
        public virtual DbSet<HotelRating> HotelRatings { get; set; }
        public virtual DbSet<HotelRoom> HotelRooms { get; set; }
        public virtual DbSet<Landmark> Landmarks { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
    }
}
