//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHotels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelLandmark
    {
        public int hotellandmark_id { get; set; }
        public int hotel_id { get; set; }
        public int landmark_id { get; set; }
        public string distance { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Landmark Landmark { get; set; }
    }
}
